name: geog6655_coherence
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.4
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.8.3
  - comm=0.2.3
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - importlib-metadata=8.7.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libcxx=21.1.0
  - libedit=3.1.20250104
  - libexpat=2.7.1
  - libffi=3.4.6
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - openssl=3.5.2
  - packaging=25.0
  - parso=0.8.5
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pip=25.2
  - platformdirs=4.4.0
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.2
  - python=3.13.7
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pyzmq=27.0.2
  - readline=8.2
  - six=1.17.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.2
  - traitlets=5.14.3
  - typing_extensions=4.15.0
  - wcwidth=0.2.13
  - zeromq=4.3.5
  - zipp=3.23.0
  - pip:
      - affine==2.4.0
      - asf-search==10.0.2
      - attrs==25.3.0
      - bleach==6.2.0
      - bokeh==3.8.0
      - branca==0.8.1
      - certifi==2025.8.3
      - charset-normalizer==3.4.3
      - click==8.2.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - contourpy==1.3.3
      - cycler==0.12.1
      - dask==2025.7.0
      - datashader==0.18.2
      - dateparser==1.2.2
      - folium==0.20.0
      - fonttools==4.59.2
      - fsspec==2025.9.0
      - geopandas==1.1.1
      - holoviews==1.21.0
      - idna==3.10
      - jinja2==3.1.6
      - kiwisolver==1.4.9
      - linkify-it-py==2.0.3
      - llvmlite==0.44.0
      - locket==1.0.0
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - multipledispatch==1.0.0
      - narwhals==2.4.0
      - numba==0.61.2
      - numpy==2.2.2
      - pandas==2.3.2
      - panel==1.8.0
      - param==2.2.1
      - partd==1.4.2
      - pillow==11.3.0
      - progressbar==2.5
      - pyct==0.5.0
      - pyogrio==0.11.1
      - pyparsing==3.2.3
      - pyproj==3.7.2
      - pytz==2025.2
      - pyviz-comms==3.0.6
      - pyyaml==6.0.2
      - rasterio==1.4.3
      - regex==2025.9.1
      - requests==2.32.5
      - rioxarray==0.19.0
      - scipy==1.16.1
      - seaborn==0.13.2
      - shapely==2.1.1
      - tenacity==9.1.2
      - toolz==1.0.0
      - tqdm==4.67.1
      - tzdata==2025.2
      - tzlocal==5.3.1
      - uavsar-pytools==0.7.1
      - uc-micro-py==1.0.3
      - urllib3==2.5.0
      - webencodings==0.5.1
      - xarray==2025.9.0
      - xyzservices==2025.4.0
prefix: /Users/julo9057/anaconda3/envs/geog6655_coherence
