name: snowex_uavsar_coherence
channels:
  - conda-forge
  - defaults
dependencies:
  - aiobotocore=2.24.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - aom=3.9.1
  - appnope=0.1.4
  - asf_search=6.3.1
  - asttokens=3.0.0
  - attrs=25.3.0
  - blosc=1.21.6
  - botocore=1.40.18
  - bounded-pool-executor=0.0.3
  - brotli-python=1.1.0
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.34.5
  - c-blosc2=2.21.3
  - ca-certificates=2025.10.5
  - cartopy=0.25.0
  - certifi=2025.10.5
  - cffi=2.0.0
  - charls=2.4.2
  - charset-normalizer=3.4.3
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - cycler=0.12.1
  - dateparser=1.2.2
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - earthaccess=0.15.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - freetype=2.14.1
  - freexl=2.0.0
  - frozenlist=1.7.0
  - fsspec=2025.9.0
  - gdal=3.11.4
  - geos=3.14.0
  - giflib=5.2.2
  - h2=4.3.0
  - hpack=4.1.0
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - imagecodecs=2025.8.2
  - imageio=2.37.0
  - importlib-metadata=8.7.0
  - importlib-resources=6.5.2
  - importlib_metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - jedi=0.19.2
  - jmespath=1.0.1
  - json-c=0.18
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jxrlib=1.1
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lazy-loader=0.4
  - lcms2=2.17
  - lerc=4.0.0
  - libaec=1.1.4
  - libarchive=3.8.1
  - libavif16=1.3.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcurl=8.14.1
  - libcxx=21.1.0
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libev=4.33
  - libexpat=2.7.1
  - libffi=3.4.6
  - libfreetype=2.14.1
  - libfreetype6=2.14.1
  - libgdal-core=3.11.4
  - libgfortran=15.1.0
  - libgfortran5=15.1.0
  - libhwy=1.3.0
  - libiconv=1.18
  - libjpeg-turbo=3.1.0
  - libjxl=0.11.1
  - libkml=1.3.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libnghttp2=1.67.0
  - libopenblas=0.3.30
  - libpng=1.6.50
  - librttopo=1.1.0
  - libsodium=1.0.20
  - libspatialite=5.1.0
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libtiff=4.7.1
  - libwebp-base=1.6.0
  - libxcb=1.17.0
  - libxml2=2.15.0
  - libxml2-16=2.15.0
  - libxml2-devel=2.15.0
  - libzlib=1.3.1
  - libzopfli=1.0.3
  - llvm-openmp=21.1.2
  - lz4-c=1.10.0
  - lzo=2.10
  - matplotlib-base=3.10.7
  - matplotlib-inline=0.1.7
  - minizip=4.0.10
  - multidict=6.6.3
  - multimethod=2.0
  - muparser=2.3.5
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.5
  - openjpeg=2.5.4
  - openssl=3.5.4
  - packaging=25.0
  - parso=0.8.5
  - pcre2=10.46
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - platformdirs=4.4.0
  - pqdm=0.2.0
  - proj=9.7.0
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycparser=2.22
  - pygments=2.19.2
  - pyproj=3.7.2
  - pyshp=3.0.2
  - pysocks=1.7.1
  - python=3.13.7
  - python-cmr=0.13.0
  - python-dateutil=2.9.0.post0
  - python_abi=3.13
  - pytz=2025.2
  - pywavelets=1.9.0
  - pyzmq=27.0.2
  - qhull=2020.2
  - rav1e=0.7.1
  - readline=8.2
  - remotezip=0.12.3
  - requests=2.32.5
  - s3fs=2025.9.0
  - scikit-image=0.25.2
  - six=1.17.0
  - snappy=1.2.2
  - sqlite=3.50.4
  - stack_data=0.6.3
  - svt-av1=3.1.2
  - tenacity=9.1.2
  - tifffile=2025.9.20
  - tinynetrc=1.3.1
  - tk=8.6.13
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzlocal=5.3.1
  - uriparser=0.9.8
  - urllib3=2.5.0
  - wcwidth=0.2.13
  - wrapt=1.17.3
  - xerces-c=3.2.5
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zfp=1.0.1
  - zipp=3.23.0
  - zlib=1.3.1
  - zlib-ng=2.2.5
  - zstandard=0.25.0
  - zstd=1.5.7
  - pip:
      - affine==2.4.0
      - asf-search==10.0.2
      - bleach==6.2.0
      - bokeh==3.8.0
      - branca==0.8.1
      - click==8.2.1
      - click-plugins==1.1.1.2
      - cligj==0.7.2
      - cloudpickle==3.1.1
      - colorcet==3.1.0
      - dask==2025.7.0
      - datashader==0.18.2
      - folium==0.20.0
      - fonttools==4.59.2
      - geopandas==1.1.1
      - holoviews==1.21.0
      - jinja2==3.1.6
      - linkify-it-py==2.0.3
      - llvmlite==0.44.0
      - locket==1.0.0
      - markdown==3.9
      - markdown-it-py==4.0.0
      - markupsafe==3.0.2
      - matplotlib==3.10.6
      - mdit-py-plugins==0.5.0
      - mdurl==0.1.2
      - multipledispatch==1.0.0
      - narwhals==2.4.0
      - numba==0.61.2
      - numpy==2.2.2
      - pandas==2.3.2
      - panel==1.8.0
      - param==2.2.1
      - partd==1.4.2
      - progressbar==2.5
      - pyct==0.5.0
      - pyogrio==0.11.1
      - pyparsing==3.2.3
      - pyviz-comms==3.0.6
      - pyyaml==6.0.2
      - rasterio==1.4.3
      - regex==2025.9.1
      - rioxarray==0.19.0
      - scipy==1.16.1
      - seaborn==0.13.2
      - shapely==2.1.1
      - toolz==1.0.0
      - tzdata==2025.2
      - uavsar-pytools==0.7.1
      - uc-micro-py==1.0.3
      - webencodings==0.5.1
      - xarray==2025.9.0
      - xyzservices==2025.4.0
prefix: /Users/julo9057/anaconda3/envs/snowex_uavsar_coherence
